import type { ProfileData } from './types';

export const profileData: ProfileData = {
  personalInfo: {
    name: "Vishnu Prajapat",
    title: "AI Full Stack Developer",
    location: "India",
    avatar: "/image/m3.JPG",
    email: "vishanuprajapati888@gmail.com",
    phone: "+91 6377749427",
    linkedin: "https://www.linkedin.com/in/vishnuprajapattt/",
    github: "https://github.com/vishprajapattt",
    portfolioUrl: "https://vishnu-portfolio.vercel.app",
  },
  summary:
    "Experienced in building complete web applications, from frontend to backend and database, often enhanced with AI to improve speed and quality.",
  skills: [
    { name: "React.js", endorsement: 25 },
    { name: "C++", endorsement: 20 },
    { name: "Python", endorsement: 18 },
    { name: "DSA", endorsement: 15 },
    { name: "Firebase", endorsement: 14 },
    { name: "Automation", endorsement: 12 },
    { name: "AI & GenAI", endorsement: 15 },
    { name: "Data Science Libs", endorsement: 10 },
  ],
  projects: [
    {
      name: "Sparrowfy",
      description: "A comprehensive SaaS platform for coaching management, optimizing student tracking and scheduling with a modern dashboard.",
      technologies: ["React.js", "API", "SaaS"],
      imageUrl: "/image/aiquizcraft.png",
      imageHint: 'coaching management',
      projectUrl: "https://aiquizcraft.com",
      githubUrl: "#",
    },
    {
      name: "InstaAutomation",
      description: "Advanced Instagram automation tool that intelligently automates comment replies and DM workflows using React.",
      technologies: ["React", "Automation"],
      imageUrl: "/image/insta.jpg",
      imageHint: 'instagram automation',
      projectUrl: "#",
      githubUrl: "#",
    },
    {
      name: "ChatWithPDF",
      description: "AI-powered tool to interact with your PDF documents, extracting information and answering questions using natural language.",
      technologies: ["React", "AI", "PDF"],
      imageUrl: "/image/chatpdf.png",
      imageHint: 'ai chat pdf',
      projectUrl: "#",
      githubUrl: "#",
    },
    {
      name: "Image & PDF Tool",
      description: "A versatile toolkit for processing images and PDFs, including conversion, compression, and editing features.",
      technologies: ["React", "Utility", "Tools"],
      imageUrl: "/image/pdf-tool.png",
      imageHint: 'pdf utility tool',
      projectUrl: "#",
      githubUrl: "#",
    },
    {
      name: "Resume Builder",
      description: "A professional web application for creating resumes easily with customizable templates and real-time assistance.",
      technologies: ["React", "Web App", "AI"],
      imageUrl: "/image/resume.png",
      imageHint: 'resume builder',
      projectUrl: "https://resume-builder-ten-black.vercel.app/",
      githubUrl: "#",
    },
    {
      name: "Online Gaming Platform",
      description: "A modern online gaming platform featuring a responsive interface and real-time game state management.",
      technologies: ["Vite", "React"],
      imageUrl: "/image/online-game.jpeg",
      imageHint: 'online gaming',
      projectUrl: "http://realonlinegaming.netlify.app",
      githubUrl: "#",
    },
  ],
  experience: [
    {
      title: "Freelance AI Full Stack Developer",
      company: "Self-Employed",
      location: "Remote",
      startDate: "Jan 2023",
      endDate: "Present",
      description:
        "Building end-to-end web applications with AI integrations, focusing on automation and high-quality user experiences.",
    },
  ],
  education: [
    {
      degree: "Bachelor of Technology",
      institution: "Your Institution Name",
      location: "India",
      startDate: "2021",
      endDate: "2025",
      description: "Focusing on Computer Science and Engineering.",
    },
  ],
};